### ISSUE TITLE
Please add "(qtranslate)" info to field label

### ISSUE THREAD

**Issue by tmconnect** [funkjedi/acf-qtranslate#123]
In order to differentiate fields in the field editor, it would be an advantage if the qtranslate fields were to be supplemented. So you could distinguish the standard fields of ACF better from the qtranslate fields.

**Comment by mayaliny** [comment]
i think that will help a lot of us, addressing problems to right solution..

**Comment by funkjedi** [comment]
Just released new version (v1.7.25) which includes these changes.

**Comment by tmconnect** [comment]
Thanks for including
