### ISSUE TITLE
ACF qTranslate 1.7.1 + Qtranslate-X bugs

### ISSUE THREAD

**Issue by fburatti** [funkjedi/acf-qtranslate#19]
The new release is much improved, thank you so much for your work! 

I report some bugs:

1) In the post editing screen (post, page and every custom post type) there is this notice:
`Notice</b>:  Undefined variable: args in <b>/Applications/MAMP/htdocs/wp/wp-content/plugins/acf-qtranslate/src/acf_5/acf.php</b> on line <b>113`

In the offending line perhaps we need to change  `acf_get_field_groups ($ args)` to `acf_get_field_groups ($ filter)`
so the ACF fields used in the screen are correctly filtered.

2) In addition, on the first loading of the edit page, the (hidden) switch-editor of acf-qtranslate fields is set to the wrong language, if the current language (stored in the administrator session) is different from the default.

3) Inside Flexible Content or Repeater, the wysiwyg editor does not save the content in any language, however the text and plain textarea field work properly

Wordpress 4.1.1
Qtranslate-X 3.2
ACF Pro 5.1.9.1
ACF qTranslate 1.7.1

**Comment by funkjedi** [comment]
Thanks for reporting back. These issue should now be resolved in the latest release 1.7.2 which I just pushed out.
