### ISSUE TITLE
Adding Content to WYSIWYG dupes in native WP Content Editor

### ISSUE THREAD

**Issue by moxyinc** [funkjedi/acf-qtranslate#2]
First off - this plugin is absolutely gorgeous - and thank you. But as mentioned on the ACF old.forum, there is the one little bug for the WYSIWYG content. It overwrites anything in the native WP content editor. Just wanted to post it here, as this area seemed more active than over there.

Again - thanks. And let me know where I can find the tip jar.

**Comment by VishalModasta** [comment]
@MaximBelov, i do not see **qtranslate_javascript.php** file anywhere in entire plugin. Please suggest how can i resolve this problem?
Anyone can help me in resolving this issue. Thanks
