### ISSUE TITLE
No tabs displayed in edit screen

### ISSUE THREAD

**Issue by Tabrisrp** [funkjedi/acf-qtranslate#20]
Hi,

I discovered your plugin for translating the ACF fields with qTranslateX, and tried to used it on a website I'm working on right now.

The problem I have is that instead of displaying each version of the fields in tabs for each language, they're displayed one below the other, and if I save, all the content for all languages is displayed together on the page.

I'm not seeing any javascript or warning/notice, so I can't really give your directions. I'm using ACF 4.4 and WP 4.1.

![edit-screen](https://cloud.githubusercontent.com/assets/3465180/6492016/82c6cd02-c2b1-11e4-8b25-48d657885b58.png)

**Comment by funkjedi** [comment]
Looks like I inadvertently introduced a bug in the last update. I've pushed out a new release which should correct the issue.

**Comment by Tabrisrp** [comment]
Yes the new release is working fine, thank you !
