### ISSUE TITLE
ACF-qTranslate doesn't render inside repeater field (ACF PRO v5.2.0 and qTranslate-X 3.2.2)

### ISSUE THREAD

**Issue by Gasimzada** [funkjedi/acf-qtranslate#21]
It works everywhere except inside the repeater field.

**Comment by funkjedi** [comment]
Which field types are you trying to use?

**Comment by fburatti** [comment]
If using qTranslate-X the standard Text, Text Area and WYSIWYG field types all automatically support translation out of the box.

Instead, I noticed that for the fields within repeater and flexible content, you must use the ACF qtranslate fields (text, textarea and wysiwyg).

In this way, it all seems to work, at least in my setup: fields are displayed and the translation correctly saved

**Comment by Gasimzada** [comment]
Thank you! The problem got fixed when I used the qtranslate text, which I just noticed until now 😃
