### ISSUE TITLE
qTranslate X with ACF Repeater

### ISSUE THREAD

**Issue by enguerranws** [funkjedi/acf-qtranslate#22]
Hi, 

this is a great plugin, thank you really much !

However, I still got an issue with qTranslate X, using Repeater fields : translation is just not effective on those fields (and fields within). Any suggestions ?

**Comment by berendvaneerde** [comment]
+1 
Same problem here with Flexible Content.

**Comment by funkjedi** [comment]
This is something I'm working to correct. The work around in the interim is to use the qTranslate field types instead of the core ACF field types.

**Comment by berendvaneerde** [comment]
Great! Good tip and looking forward to the fix!

**Comment by enguerranws** [comment]
So we currently can't use translations on Repeaters ?

**Comment by fburatti** [comment]
No you can! everything works!

From the documentation: "If using the standard X-qTranslate Text, Textarea and WYSIWYG field types to automatically support translation out of the box..."

However, within the flexible content or repetear, you have to use the  acf-qtranslate fields (Text, Textarea and WYSIWYG)

**Comment by funkjedi** [comment]
The standard X-qTranslate Text, Textarea and WYSIWYG are not working correctly inside repeats.

**Comment by berendvaneerde** [comment]
exactly that's the problem. I can't delete the repeats. I could change the
normal WYSIWYG's etc. into X-qTranslate fields if necessary, but it
wouldn't solve the issue that nothing is saved when the plugin is active
and there are Flexible Content or Repeater Fields present.


2015-03-26 5:18 GMT+01:00 Tim Robertson <notifications@github.com>:

**Comment by funkjedi** [comment]
Sorry meant to say they are "now" working.

**Comment by berendvaneerde** [comment]
GREAT! Thank you so much... Working like a charm...

**Comment by pepodebu** [comment]
Thanks for this excellent plugin. I'm trying to use it with ACF Pro but everytime I save my contents all the repeater fields get deleted.

I think this is not the case with ACF4 (tested also), but in ACF5 this continue to be a bug. Thank you very much for your help.

**Comment by pepodebu** [comment]
AFC Versión 5.2.2
Advanced Custom Fields: qTranslate Versión 1.7.6
qTranslate-X Versión 3.2.9

If I can help you with anything else, you're welcome.

**Comment by ondrejruzicka** [comment]
Same here. Actual versions of plugins:
AFC  - 5.2.2
ACF qTranslate - 1.7.6
qTranslate X  - 3.2.9

qTranslte text field / qTranslate wysiwyg field in repeater are not saving.

Thanks for your effort and good job.

**Comment by ondrejruzicka** [comment]
Yay, my bad. It´s working now. Probably closing web browser helped (clearing JS cache). Could help somebody...
