### ISSUE TITLE
ACF4 + qTranslate-X > WYSIWIG doesn't work

### ISSUE THREAD

**Issue by Twinski** [funkjedi/acf-qtranslate#23]
Hi there!

Everything seems to work fine ( textfields ) but the ACF WYSIWIG field doesn't. It is the same content for English, German and Chinese for example. Is it something you guys are still working on or should I update to ACF5? 

Looking forward hearing from you and keep up the good work!
Yordi

**Comment by funkjedi** [comment]
Try testing again with the latest release and let me know if you're still having problems.
