### ISSUE TITLE
ACF qTranslate + qTranslate-x / Media don't show up

### ISSUE THREAD

**Issue by franciurachel** [funkjedi/acf-qtranslate#24]
I run both plugins and my Media page is empty even if Im still able to upload images (from both the page itself and posts and pages) and the images I had uploaded earlier still work.

Do you have any idea?

If I disable one of the 2 plugins the problem is solved

**Comment by Kristjan-Reinsberg** [comment]
Same here. Also tried clean install with up to date plugins.


..advanced-custom-fields/js/input.min.js?ver=4.4.1:1 Uncaught TypeError: Cannot read property 'post_id' of null

Google crome inspector jumps here.... 
$(document).ready(function(){if(acf.screen.post_id=acf.o.post_id,...

**Comment by franciurachel** [comment]
I found out a woorkaround - not proper solution - cos I think is a damn bug.

Just deactivate one of the 2 plugins and go to Media page.
Now you can see all your media. Change to List View
and then reactivate the plugin.

You should keep seeing the media now.

I had the same problem with Categories and Taxonomies translation: with the 2 plugins activated I could not translate anything, but with this workaround you can and then even if you dont see the translation in the backend, it works in the frontend.

**Comment by Kristjan-Reinsberg** [comment]
does anyone knows some version bundle that works? ....some older WP+qtranslateX+acf-q

**Comment by panchobes** [comment]
Same problem, I tried with the franciurachel solution but the problem persists when you switch back to the grid media display.

**Comment by funkjedi** [comment]
I'll be pushing out an update later tonight with fixes for this and a few
other bugs.

**Comment by diego-betto** [comment]
Thank you Tim!

**Comment by Kristjan-Reinsberg** [comment]
Bought ACF PRO version. Works like a charm!

**Comment by funkjedi** [comment]
New release with fix is live in the Plugin Directory.

**Comment by panchobes** [comment]
Thank you Tim, it works!!!

**Comment by Ps1996** [comment]
I have the same problem like a year before franciurachel had. If I install the plugin I can't open the media library. I'm using ACF Pro 5.5.4

**Comment by funkjedi** [comment]
The error was related to a change in the File field introduced in ACF 5.5.4 which was just released this morning.
