### ISSUE TITLE
Problems with ACF qTranslate & Custom Post Type UI 1.0.5

### ISSUE THREAD

**Issue by brunogdesign** [funkjedi/acf-qtranslate#26]
Hi!

I'm having some issues with this plugin and Custom Post Type when Wordpress debug mode is active. I'm getting this error when accessing any of the CPT menus on Wordpress:
"Trying to get property of non-object in /Applications/MAMP/htdocs/wp_tourism360/wp-content/plugins/acf-qtranslate/src/acf_4/acf.php on line 152"

![screen shot 2015-04-02 at 11 17 34](https://cloud.githubusercontent.com/assets/1450050/6962162/e6b6cf7c-d929-11e4-9cc8-1dd38c6fc23e.png)

Am I the only one? Can anyone help me?

Best regards,
Bruno Garcia

**Comment by funkjedi** [comment]
Fixed in the latest release.

**Comment by brunogdesign** [comment]
Thanks :D
