### ISSUE TITLE
Translating advanced custom fields labels, descriptions, etc

### ISSUE THREAD

**Issue by brunogdesign** [funkjedi/acf-qtranslate#27]
Hi again 

When i'm creating an Advanced Custom field group i'm easily able to give a group name in every language i'm supporting... but I can't find a way to give different labels and instructions to the fields themselves... When en switch between flags/languages, only the field group name is getting internationalised, everything else stays the same.

I want to create a field with a label "Case study type" inside a "Case Study" field group. Then I want to change that label according to the user language, for example "Estudo de caso" in Portuguese. I want to do this with all the other stuff like Field Instructions and Options (if the field type is a select box).

Is this already possible? Can someone help me?

**Comment by funkjedi** [comment]
It's not currently supported but you could do it your self by adding the display hooks. Something like this: 
```php
add_action('admin_head', 'add_acf_label_translations');
function add_acf_label_translations() {
?>
<script>
jQuery(function($) {
	$(window).load(function() {

		// only proceed if qTranslate-X is loaded
		if (!qTranslateConfig || !qTranslateConfig.qtx) {
			return;
		}

		var uniqueId = 0;

		// Add display hooks to labels
		$('.acf-label label').each(function() {
			this.id = 'acf-label--' + (uniqueId++);
			qTranslateConfig.qtx.addDisplayHookById(this.id);
		});

	});
});
</script>
<?php
}
```

**Comment by brunogdesign** [comment]
I didn't spend a lot of time with your solution because I couldn't find a way to make it work... then i found this: [Tutorial](http://support.advancedcustomfields.com/forums/topic/qtranslate-shorttags-in-field-labels/) and that worked.

Anyway, it would be awesome to have this kind of support out of the box with this great plugin... is this in the roadmap?

Thank you for your support!
