### ISSUE TITLE
bug when editing fields (old value of one language gets appended to value of other language)

### ISSUE THREAD

**Issue by beta2k** [funkjedi/acf-qtranslate#30]
i use the following relevant plugins:
Advanced Custom Fields (4.4.1)
Advanced Custom Fields: qTranslate (1.7.6)
qTranslate-X (3.2.9)

i have a custom post type called `films` with custom fields for two languages `english` and `german`. the custom fields are using the qTranslate field type.

i have a problem when editing one language of a field and then updating it. for instance i have the field `Titel`. initially for english it contains `AlmaEN` (http://i.imgur.com/UzlSB8U.png) and for german it contains `AlmaDE` (see: http://i.imgur.com/bk5joTi.png). if i edit the english version to `AlmaEN2` and hit update, a strange thing happens: the german-version of the field gets appended the old value of the english field, i.e., `AlmaEN`. the english version updates as expected. see this screenshot for the resulting values of both fields. the deutsch/german version contains the strange value: http://i.imgur.com/bVCgquN.png

i dont know much about the internals of these plugins, so i have no idea why/where this happens.

i would love to have this fixed, because it makes editing the multilanguage custom fields really tedious...

please note that i also made this change: https://wordpress.org/support/topic/language-switcher-for-custom-fields?replies=3

thanks!

**Comment by beta2k** [comment]
edit: the bug appears to only happen for simple "text" field types. i tried with a WYSIWYG field type and the bug did not appear.

**Comment by funkjedi** [comment]
Fixed in the latest release.
