### ISSUE TITLE
WYSIWYG missing buttons with acf

### ISSUE THREAD

**Issue by schnapi** [funkjedi/acf-qtranslate#31]
I use the following plugins:
Advanced Custom Fields (4.4.1)
Advanced Custom Fields: qTranslate (1.7.6)
qTranslate-X (3.2.9)

Some buttons are missing in acf wysiwyg. There is no link button and some others are missing too.

thanks!

![capture](https://cloud.githubusercontent.com/assets/4158121/7510368/7dda7624-f49b-11e4-9ec5-db9781511791.PNG)

**Comment by funkjedi** [comment]
See the Advanced Custom Fields documentation of information about customizing the toolbars.
http://www.advancedcustomfields.com/resources/customize-the-wysiwyg-toolbars/

**Comment by schnapi** [comment]
Still not working. 

If I deactivate Advanced Custom Fields: qTranslate plugin the link button apper in wysiwyg editor (image below)

![capture](https://cloud.githubusercontent.com/assets/4158121/7541729/bde014d2-f5b7-11e4-9e10-f3ac2df01458.PNG)

And when the plugin is activated there is no link button.

![capture1](https://cloud.githubusercontent.com/assets/4158121/7541767/f0a2fd30-f5b7-11e4-8bdf-e0b22ad96f92.PNG)

I am using this code in my function.php:


function customize_acf_wysiwyg_toolbar( $toolbars ) {
    // Uncomment to view format of $toolbars
	/*
	echo '< pre >';
		print_r($toolbars);
	echo '< /pre >';
	die;
	*/
  // Edit the "Full" toolbar and add 'fontsizeselect' if not already present.
  //if (($key = array_search('link' , $toolbars['Full'][1])) !== true) {
    array_push($toolbars['Full'][1], 'link');
  //}

  // return $toolbars - IMPORTANT!
  return $toolbars;
}

add_filter('acf/fields/wysiwyg/toolbars' , 'customize_acf_wysiwyg_toolbar');

Thanks!

**Comment by funkjedi** [comment]
Interesting. It looks like `wp_editor` was being called multiple times for the `acf_settings` editor which was reseting the toolbars to the default. I've just pushed out an update which should fix this.
