### ISSUE TITLE
ACF PRO not work

### ISSUE THREAD

**Issue by roccraq** [funkjedi/acf-qtranslate#32]
Hello, I can't use ACF PRO with qTranslate-X.

I have this plugin installed:
ACF PRO version 5.2.3
qTranslate-X version 3.3
ACF qTranslate version 1.7.6

The problem incurred when using a repeater. When save post with a repeater field page returns follow error.
If I use ACF normal, not PRO, with the same other plugins, all work properly.

Anyone can help me?

Warning: Illegal string offset 'field_5548b2b971eab' in /Users/cr/wp-content/plugins/qtranslate-x/admin/qtx_configuration.php on line 37

Warning: Illegal string offset 'en' in /Users/rocco/Dropbox/cr/wp-content/plugins/qtranslate-x/admin/qtx_configuration.php on line 37

Warning: Illegal string offset 'it' in /Users/cr/wp-content/plugins/qtranslate-x/admin/qtx_configuration.php on line 37

Warning: Cannot modify header information - headers already sent by (output started at /Users/rocco/Dropbox/localhost/cinemaritrovato/wp-content/plugins/qtranslate-x/admin/qtx_configuration.php:37) in /Users/cr/wp-includes/pluggable.php on line 1196.

**Comment by Fibiuz** [comment]
Same situation here.

**Comment by funkjedi** [comment]
I'll be pushing out an update later tonight that addresses a number of issues related to the recent changes in qTranslate-X.

**Comment by roccraq** [comment]
Thank you very much and congratulations for the work.
I'll wait for the update.

**Comment by Fibiuz** [comment]
Thank you funkjedi,
I really appreciate your work.

**Comment by Fibiuz** [comment]
I've just updated to the latest version (1.7.7)
It works like a charm!
Thank you funkjedi

**Comment by roccraq** [comment]
I have just tested, amazing, work perfectly!

Thank you!!!


Il giorno 07/mag/2015, alle ore 08:09, Fibiuz <notifications@github.com> ha scritto:
