### ISSUE TITLE
Not parsing existing fields with qtranslate-x

### ISSUE THREAD

**Issue by loganyott** [funkjedi/acf-qtranslate#35]
Greetings!

I am using the following:
acf-qtranslate v1.7.9
advanced-custom-fields v 4.4.1
qtranslate-x v3.3

Most fields seem to work fine. My main problem is the `wysiwyg` field.

If I use the "standard" field translation, the WYSIWYG field is loaded with the content from the current language, but no others. Switching the language works, but all languages are defaulted to whatever the language is when I load the page. Example: If I load the page in English, the english field value is used for all languages. If I load in chinese, chinese field value is used for all languages.

If I don't use the "standard" field translation and add the language tabs, I get all languages displayed in the wysiwyg field. If I add the content and switch the language tab, it transfers the new content correctly. However, existing content for all languages is loaded in every languages box.

Have you seen an issue like this or any ideas on where I should debug first? If it helps, I semi-recently migrated from mqtranslate to qtranslate-x, so these fields are currently stored with `<!--:-->` tags instead of the new `[:]`.

Thanks!

**Comment by Tusko** [comment]
https://goo.gl/yx1Z3r
this works fine
