### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by runbing** [funkjedi/acf-qtranslate#36]
It's showing "Uncaught SyntaxError: Unexpected token <" when I put my site on my nginx server ( but normal in my local Apache server ).

![2015-05-21 2 47 37](https://cloud.githubusercontent.com/assets/488066/7734128/7384fb74-ff66-11e4-97c0-8a9a47b998b4.png)

When I changed this code block:

&lt;script&gt;
var acf_qtranslate_translate_standard_field_types = &lt;?= json_encode($translate_standard_field_types) ?&gt;;
&lt;/script&gt;

to:

&lt;script&gt;
var acf_qtranslate_translate_standard_field_types = &quot;1&quot;;
&lt;/script&gt;

it seem worked, but I do not know where is the problem. Would you help me? thanks.

---------------

Advanced Custom Fields :  Version 4.4.2
Advanced Custom Fields: qTranslate : Version 1.7.9
qTranslate-X : Version 3.3.1

**Comment by funkjedi** [comment]
If you're not running PHP 5.4+ you need to have `short_open_tag` enabled to allow the use of the short echo tag (i.e. `<?=`).

**Comment by runbing** [comment]
Oh yeah!!! It's worked!!! Thank a lot for your help, funkjedi. ^_^

**Comment by Fibiuz** [comment]
Hi funkjedi,

I got the same error.
The short_open_tag is enabled

If I disable the ACF qTranslate the console doesn't show error.
- - -
Wordpress 4.5.2
ACF qTranslate 1.7.9
ACF 5 Pro 5.3.7
qtranslate-X 3.4.6.7

**Comment by shankiesan** [comment]
Likewise @funkjedi I'm having the same problem but on `post-new.php` (and only when ACF Qtrans is enabled).

----
Wordpress 4.5.2
ACF qTranslate 1.7.9
ACF 5 Pro 5.3.8.1
qtranslate-X 3.4.6.8

**Comment by shankiesan** [comment]
My colleague figured out where the problem is coming from. I can work around it by killing warnings on the prod server, but would still be good to get to the bottom of it. Here's the error:

`<b>Warning</b>:  call_user_func_array() expects parameter 1 to be a valid callback, class 'acf_qtranslate_acf_5_wysiwyg' does not have a method 'input_admin_footer_js' in <b>/var/www/html/wp-includes/plugin.php</b> on line <b>525</b><br />`

**Comment by LukasLt** [comment]
ACF pro has renamed admin footer function in 5.3.7
```
fields/wysiwyg.php:
-		add_action('acf/input/admin_footer_js', 	array($this, 'input_admin_footer_js'));
+		add_action('acf/input/admin_footer', 	array($this, 'input_admin_footer'));
```

also 
```
File core/media.php
-		add_action('acf/input/admin_footer_js', 	array($this, 'admin_footer_js'));
+		add_action('acf/input/admin_footer', 		array($this, 'admin_footer'));
```
