### ISSUE TITLE
ACF Image (qtranslate_image) not saved

### ISSUE THREAD

**Issue by diego-betto** [funkjedi/acf-qtranslate#37]
Hi,

Image fields are not saved (empty on refresh)

Post request seems ok (example using only DE)

fields[field_53fe04c112554][0][field_555de2cdde174][de]:1402
fields[field_53fe04c112554][0][field_555de2cdde174][en]:
fields[field_53fe04c112554][0][field_555de2cdde174][it]:

But values are not saved ( field_555de2cdde174 is not present in *_postmeta table )

ACF 4.4.2
ACF qTranslate: 1.7.9
qTranslate-X: 3.3
Wordpress: 4.2.2

Any idea?

Tnx

**Comment by macdonaldr93** [comment]
I'm having the same issue with the same plugins and versions

**Comment by diego-betto** [comment]
Bump

**Comment by NielsHavermans** [comment]
Use qTranslate-x version 3.2.9 (https://wordpress.org/plugins/qtranslate-x/developers/)
This solved the problem for me.

**Comment by loganyott** [comment]
I am experiencing this issue as well. I'd rather not revet to qtranslate-x 3.2.9 though. Does anyone have a lead on where to debug further or a fix that hasn't been posted?

**Comment by macdonaldr93** [comment]
I'm in the same boat, I don't really want to revert to 3.2.9 but I haven't seen any other issues.

**Comment by loganyott** [comment]
Has anyone made progress on enabling translation for the standard field type rather than the `qtranslate_image` one? That seems to be the sustainable path forward.

**Comment by loganyott** [comment]
Tried making a standard field translation implementation to fix this. See PR #47.

**Comment by diego-betto** [comment]
Thank you loganyott, I'll try your fix!

**Comment by loganyott** [comment]
So I found that I can use the media uploader, select an image, and save the image for that field. However, it looks like #47 does not properly translate the image field, as selecting a different image in one language changes every other language to that value. Did you see that too @diego-betto ?

**Comment by terrayi** [comment]
Could this be fixed soon?
