### ISSUE TITLE
qtranxf_getLanguage() not working in ajax 

### ISSUE THREAD

**Issue by circularone** [funkjedi/acf-qtranslate#41]
I've been using qtranxf_getLanguage() to get the current language within ajax calls for some time and it's been working fine.

The client updated the wordpress core to 4.2.2 and now that function isn't working within ajax calls although it is functioning normally otherwise.

I've tried versions from 2.9.6 - 3.3 of  qtranslatex with the same problem.

Has anyone experienced this and/or know of a fix?

Cheers

**Comment by Tusko** [comment]
site.com/wp-admin/ajax-admin.php?lang=your_language_code
