### ISSUE TITLE
WYSIWYG FIeld (ACF 4) doesn't separate the language values when loading data from database

### ISSUE THREAD

**Issue by dpsjorge** [funkjedi/acf-qtranslate#42]
The WYSIWYG field for ACF 4 loads all languages values when editing in the admin area, because it sends the whole field value (without using the value for each language). Here is the area of the code with the problem ($field['value'] contains the string with all languages, $value contains the string with the value for the language on the loop, please check the value inside of the text area):

![captura de tela 2015-06-05 as 17 08 37](https://cloud.githubusercontent.com/assets/3978744/8014339/431cd6b8-0ba6-11e5-99b1-e6549e5b874f.png)

And here is the fix:

![captura de tela 2015-06-05 as 17 08 58](https://cloud.githubusercontent.com/assets/3978744/8014343/4f1614fc-0ba6-11e5-93aa-41d67a61b6a0.png)

**Comment by ErikHarmon** [comment]
@dpsjorge , do you have to do this also for the else clause right below,

  echo wp_htmledit_pre( $field['value'] );

...also? Apologies if this is obvious, I am unfamiliar with the internals of WP.

**Comment by dpsjorge** [comment]
Yes, it would be the same, but inside of the else it would be:

echo wp_htmledit_pre( $value );

instead of 

echo wp_htmledit_pre( $field['value'] );

(The second code is what it is already present in the code)

**Comment by ErikHarmon** [comment]
Excellent, thank you. You have saved me having to revert my site :-)

**Comment by Reghyz** [comment]
thanks a lot ! you've saved my day !  this bug seems to be still present in the last version (179) of the plugin ...

**Comment by thibop** [comment]
Great solution !

**Comment by alexmos26** [comment]
Any idea if this problem will be fixed in the next version of the plugin?

**Comment by miguelgd** [comment]
te quiero, jorge. Thank you!

**Comment by infiniteloopcorp** [comment]
@dpsjorge You are a life saver! Lots of love!

**Comment by dpsjorge** [comment]
I'm closing this as the issue is already fixed.
Thanks!

**Comment by marttihyvonen** [comment]
This saved my day, fix perfectly worked. If someone is looking which file to edit it's acf-qtranslate > src > acf_4 > fields > wysiwyg.php and row 100.  And this was in version 1.7.9.

**Comment by estudio3551** [comment]
09/August/2016 and still works this solution,.. Thanks
