### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by tmconnect** [funkjedi/acf-qtranslate#48]
I using WP 4.2.4, qTranslate-X 3.4.3, ACF Pro 5.2.8 and ACF qTranslate 1.7.9 and on post/page edit page I get an error on console

TypeError: undefined is not a function (evaluating 'qTranslateConfig.qtx.addContentHooksTinyMCE()')

for acf-qtranslate/assets/acf_5/qtranslatex.js line 77.

Any Idea what causes this error?

Thanks
Thomas

**Comment by DavidPeralvarez** [comment]
Hi Thomas!

Did you find any solution? I'm having the same error but with WP 4.3.1.

Thanks in advance!

**Comment by tmconnect** [comment]
No, I didn't - did you find something in the meantime.

**Comment by DavidPeralvarez** [comment]
Hi again! I dit what @fburatti said in https://wordpress.org/support/topic/js-error-qtranslateconfigqtxaddcontenthookstinymce-1?replies=3 and it worked fine. Good luck!

**Comment by tmconnect** [comment]
David, thanks for this tip.
