### ISSUE TITLE
Cannot work with ACF distributed in theme.

### ISSUE THREAD

**Issue by hinet2013** [funkjedi/acf-qtranslate#54]
##RATIONALE:##
It checks for ACF presence in response to 'plugins_loaded' action..
that check get executed before the theme (and subsequently ACF) get loaded

##A SOLUTION PROPOSAL:##
Could be to make your plugin embeddable in theme too but:

- requires the main initialization routine to be called later than 'plugins loaded'
- requires to update all 'wp_enqueue_script' occurrences that now are making use of 'plugins_url' API
- cannot be updated anymore
- is allowed to include your plugin in a theme?

Thanks for your attention

**Comment by Tusko** [comment]
@hinet2013 can you show code how you add ACF in theme?

**Comment by hinet2013** [comment]
It doesent matter how ACF is included in theme.
acf-qtranslate chooses to activate with this code: `if (function_exists('acf')) {...}`
Since ACF is included by theme code (so after all plugins get loaded..) the call fails.

The solution should be to move the acf-qtranslate activation conditional on a later hook
However my inclusion code is simply: include_once(get_stylesheet_directory() . '/xxx/acf/acf.php');

**Comment by funkjedi** [comment]
Inclusion from a theme should now work properly. I've moved the checks from `plugins_loaded` to `after_setup_theme`.
