### ISSUE TITLE
wysiwyg fields cloning each other

### ISSUE THREAD

**Issue by kstudiofx** [funkjedi/acf-qtranslate#56]
I've looked through the threads and seen the fixes for these but none of them seem to be working for me.  I'll edit both fields and click the update button and whatever language i left off with is what takes over both languages.  One thing i do notice is that every once in awhile of updating the page, I get errors and am wondering if that could be the culprit.  Any help is very appreciated.  Thank you in advance. here they are:  

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Invalid argument supplied for foreach() in /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14

Warning: Cannot modify header information - headers already sent by (output started at /home/nerd/public_html/campt/wp-content/plugins/qtranslate-x/admin/qtx_admin.php:14) in /home/nerd/public_html/campt/wp-includes/pluggable.php on line 1207

**Comment by kstudiofx** [comment]
I contacted qtranslate directly about the issue and was told to contact you.  Here's what they mentioned:

there shows an error in java console:

Uncaught TypeError: qTranslateConfig.qtx.addContentHooksTinyMCE is not a function

coming from the source

/wp-content/plugins/acf-qtranslate/assets/acf_5/qtranslatex.js?ver=4.3.1

which belongs to "Advanced Custom Fields: qTranslate".

**Comment by fburatti** [comment]
@kstudiofx read  read this  https://github.com/funkjedi/acf-qtranslate/issues/49#issuecomment-147985004

**Comment by kstudiofx** [comment]
That was PERFECT!  Thank you so much @fburatti you saved me
