### ISSUE TITLE
switchEditors.switchto(this) deprecated since WP 4.3

### ISSUE THREAD

**Issue by jdebuchy** [funkjedi/acf-qtranslate#60]
As this discussion suggest http://support.advancedcustomfields.com/forums/topic/fix-for-switcheditors-since-wordpress-4-3/

Need to replace onclick="switchEditors.switchto(this);" for data-wp-editor-id="<?php echo $id; ?>" on line 144 and 145 of src/acf_5/fields/wysiwyg.php

I tried it on ACF5 and working correctly.

Also removed lines 37 to 46 on assets/common.js

**Comment by mohdqasim98** [comment]
Worked Great! Issue is solved.
