### ISSUE TITLE
qtranslate_image incorrect structure [fix]

### ISSUE THREAD

**Issue by esiao** [funkjedi/acf-qtranslate#61]
Using ACF Pro 5.3.4 and ACF qTranslate 4.2.2 from https://github.com/fburatti/acf-qtranslate
The image field schema is not working, resulting in a javascript error and the data not being saved.

It's an easy fix, transform :

```
acf.fields.qtranslate_image = acf.fields.image.extend({
	type: 'qtranslate_image',
	focus: function() {
		this.$el = this.$field.find('.acf-image-uploader.current-language');
		this.o = acf.get_data(this.$el);
	}
});
```

to

```
acf.fields.qtranslate_image = acf.fields.image.extend({
	type: 'qtranslate_image',
	focus: function() {
		this.$el = this.$field.find('.acf-image-uploader.current-language');
		this.$input = this.$field.find('[data-name="id"]');
		this.$img = this.$field.find('[data-name="image"]');

		this.o = acf.get_data(this.$el);
	}
});
```

ACF uses the $img reference and since it was undefined crashed. Hope this will help some people.

**Comment by dayone80** [comment]
@esiao I had the same problem. This code was very helpful for me. And I found the another issue by using this code. When I switched the language and set the separate images, all language fields were set by the same image. So I should get data for each fields.

from 
```
        this.$input = this.$field.find('[data-name="id"]');
        this.$img = this.$field.find('[data-name="image"]');
```

to
```
    this.$input = this.$el.find('[data-name="id"]');
    this.$img = this.$el.find('[data-name="image"]');
```

thanks.
