### ISSUE TITLE
cannot delete repeater row

### ISSUE THREAD

**Issue by Reghyz** [funkjedi/acf-qtranslate#63]
WordPress 4.4.2
Advanced Custom Fields Pro 5.3.7
Advanced Custom Fields: qTranslate 1.7.9
qTranslate-X 3.4.6.4

here is my ACF structure in my admin : 

- flexible fields
    - a flexible field bloc with :
              - checklist field
              -tabs fields ( displayed by conditionnals comments )
                - with repeaters fields inside them ( display set on rows ) 

i cant delete added repeaters rows, all i got is this js error   : 

qtranslatex.js?ver=4.4.2:90 Uncaught TypeError: Cannot read property '$el' of undefined

i've looked inside qtranslatex.js , near line 88 : 

```
	var _hooked_repeater_remove = acf.fields.repeater.remove;
		acf.fields.repeater.remove = function(event) {

			var row = event.$el.closest('.acf-row');

```

row seems to be undefined, 

if i do  :  console.log(  event.attr('class') )  it returns me ''acf-row" , is it the wanted one ?  

maybe the scope has changed between plugins versions ?

if i set  var row = event;   i dont have error anymore, but in the same time if i comment all the function it seems to works too.

does event return the correct row  ?

**Comment by funkjedi** [comment]
Fixed in new release (1.7.11).
