### ISSUE TITLE
JS error on flexible content fields

### ISSUE THREAD

**Issue by Kieran-Calvert** [funkjedi/acf-qtranslate#66]
Thanks for your work.

I love the plugin and it is constantly saving me creating numerous fields over and over again.

WordPress: Version  4.5.2
Q Translate x : Version: 3.4.6.8
ACF qTranslate: Version: 1.7.9

The is a JS error on flexible content fields that basically loads the admin page again on top of itself if you collapse or expand a row or sometimes if you just edit a WYSIWYG field:

TypeError: qTranslateConfig.qtx.addContentHooksTinyMCE is not a function. (In 'qTranslateConfig.qtx.addContentHooksTinyMCE()', 'qTranslateConfig.qtx.addContentHooksTinyMCE' is undefined)

<img width="1059" alt="screen shot 2016-05-18 at 13 17 59" src="https://cloud.githubusercontent.com/assets/1979014/15358200/00798ee8-1cfb-11e6-8f3c-1a5996f47b35.png">

**Comment by luhengqi** [comment]
I had same problem.

**Comment by VitaliyKaplya** [comment]
same problem! help, please :)

**Comment by dualjack** [comment]
Exactly the same!

**Comment by luhengqi** [comment]
I found the solution, need to manual fix code, try it.

Fix:

Open acf-qtranslate/scr/acf_5/fields/wysiwyg.php at line 53 and replace:

`add_action('acf/input/admin_footer_js', array($this, 'input_admin_footer_js'));`

with

`add_action('acf/input/admin_footer', array($this, 'input_admin_footer'));`

**Comment by aunruh** [comment]
did not work for me :)

**Comment by funkjedi** [comment]
Fixed in new release (1.7.11).
