### ISSUE TITLE
Error not saving paragrafs on WYSIWYG

### ISSUE THREAD

**Issue by drosendo** [funkjedi/acf-qtranslate#69]
Using VISUAL editor tab.

On edit post.

**Example (Original):**

`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper diam nec efficitur viverra. Aenean vitae molestie ante.`

**Example (On change and exepected):**

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Etiam ullamcorper diam nec efficitur viverra.
Aenean vitae molestie ante.
```

**Example (Result after save):**

`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper diam nec efficitur viverra. Aenean vitae molestie ante.`
###### 

All "enter (keyboard)" paragrafs disapear, also " " disapears and gets replaces with "white spaces".

If I disable the plugin the **paragrafs** show up.

Please reply asap.

**---- Versions ----**
ACF v5.3.9.2
WP v4.5.3

Thanks,
David

**Comment by stirlingsohn** [comment]
Im experiencing exactly the same Problem.
ACF 5.4.8
ACF:qTranslate 1.7.17
qTranslate-X 3.4.6.8

Cheers

**Comment by nestorochoa** [comment]
Same problem

**Comment by stirlingsohn** [comment]
Solved it by using the 'qTranslate WYSYWIG' field instead of regular ACF WYSYWIG field.
The qTranslate fieldtypes are the last in the list of available types in the fieldgroup editing view.

**Comment by inigonz** [comment]
I have the same problem in the content editor. I tried the solutions of the previous comments but it does not work for me.

ACF 4.4.11
ACF:qTranslate 1.7.23
qTranslate-X 3.4.6.8
WP: 4.8.1

Thanks

**Comment by drosendo** [comment]
I just stopped using it.
