### ISSUE TITLE
Duplicate left admin main menu

### ISSUE THREAD

**Issue by marcwilmesdesign** [funkjedi/acf-qtranslate#75]
**Advanced Custom Fields: qTranslate Version 1.7.9**
ACF Version 5.4.6-RC1
Wordpress Version 4.6.1

when create new Flexible Content Field with qtranslate field then duplicate left admin (wordpress) main menu and backend layout is broken.
Any sugestions?

**Comment by Kieran-Calvert** [comment]
I have the same issue so I have not used the plugin for the past 4 months

**Comment by marcwilmesdesign** [comment]
No solution/update for the plugin?

Viele Grüße,
Attila Simon

**Comment by riverofjanuary** [comment]
There seems not to be. I am about to abandon the plugin but is there any other custom way to use WYSIYWYG fields?

**Comment by fburatti** [comment]
Try this fork: https://github.com/fburatti/acf-qtranslate

**Comment by marcwilmesdesign** [comment]
Thank you!

**Comment by funkjedi** [comment]
fburatti's fixes have been merged in new release (1.7.10).
