### ISSUE TITLE
qtranslatex.js?ver=4.6.1:77 Uncaught TypeError: qTranslateConfig.qtx.addContentHooksTinyMCE is not a function

### ISSUE THREAD

**Issue by aunruh** [funkjedi/acf-qtranslate#77]
I'm getting this error in the console:
qtranslatex.js?ver=4.6.1:77 Uncaught TypeError: qTranslateConfig.qtx.addContentHooksTinyMCE is not a function

using:

Advanced Custom Fields PRO: Version 5.4.8
Advanced Custom Fields: qTranslate Version 1.7.10
qTranslate-X: Version 3.4.6.8 

Thanks a lot for your great plugin!

**Comment by funkjedi** [comment]
Fixed new release (1.7.11).
