### ISSUE TITLE
qtranslatex.js?ver=4.6.1:84 Uncaught TypeError: Cannot read property 'closest' of undefined

### ISSUE THREAD

**Issue by aunruh** [funkjedi/acf-qtranslate#78]
I'm getting this error in the console:
qtranslatex.js?ver=4.6.1:84 Uncaught TypeError: Cannot read property 'closest' of undefined

I'm having a wysiwyg field in a repeater and I'm getting this error whenever I try to remove a row from the repeater. This error prevents me from removing a row from the repeater :D

using:

Advanced Custom Fields PRO: Version 5.4.8
Advanced Custom Fields: qTranslate Version 1.7.10
qTranslate-X: Version 3.4.6.8

**Comment by funkjedi** [comment]
Fixed new release (1.7.11).
