### ISSUE TITLE
Update to 1.7.11

### ISSUE THREAD

**Issue by Tusko** [funkjedi/acf-qtranslate#79]
Hi! After update have an error:

`Fatal error: Call to undefined method acf_qtranslate_acf_5_wysiwyg::add_filters() in /http_pub/urbanideas.com.ua/wp-content/plugins/acf-qtranslate/src/acf_5/fields/wysiwyg.php on line 38`

**Comment by Tusko** [comment]
sorry. I had an old version of ACF PRO

**Comment by pouyaist** [comment]
How did you update ACF?

**Comment by Tusko** [comment]
@pouyaist what you mean? I bought it :)

**Comment by pouyaist** [comment]
I am sorry... I am new in wordpress and PHP and I donno anything about ACF

**Comment by Tusko** [comment]
@pouyaist don't worry, you'll learn quickly. Wordpress is so simple.

**Comment by pouyaist** [comment]
The problem is I cannot access to my dashboard because of this error. I am not sure how to update ACF? I would be happy If you can help me

**Comment by Tusko** [comment]
@pouyaist https://www.sitepoint.com/a-guide-to-updating-wordpress/

**Comment by Tusko** [comment]
turn off `WP_DEBUG`

https://codex.wordpress.org/Debugging_in_WordPress
the section `Example wp-config.php for Debugging`

**Comment by pouyaist** [comment]
It was already off

**Comment by pouyaist** [comment]
Thanks I solved it
