### ISSUE TITLE
ACF Translate field types dissapeared in wp-admin

### ISSUE THREAD

**Issue by Ma3oBblu** [funkjedi/acf-qtranslate#80]
all was good before. I've used acf qtranslate fields in project. but now i don't see acf qtranslate field types in custom fields admin panel. and old field don't work now. 

qtranslate-x 3.4.6.8
acf 4.4.11
acf qtranslate 1.7.13

on first screen old fields that were with acf qtranslate type
on second screen there are no acf qtranslate field types when creating custom field
on third screen setting for acf qtranslate
on fourth and fifth screens integration settings for qtranslate-x

tried to deactivate q-transale-x, saving integration settings, removing checkboxes from acf qtranslate settings

tried to install acf qtranslate and qtranslate-x to another site - the same problem

WP version is 4.6.1

![1](https://cloud.githubusercontent.com/assets/6071315/19723818/31020128-9b8e-11e6-9f91-3820c85d676d.png)
![2](https://cloud.githubusercontent.com/assets/6071315/19723817/3100455e-9b8e-11e6-910c-5c703dc605ae.png)
![3](https://cloud.githubusercontent.com/assets/6071315/19723872/7072efb6-9b8e-11e6-8b0e-1e082a949054.png)
![4](https://cloud.githubusercontent.com/assets/6071315/19723871/7072c3ec-9b8e-11e6-9388-0a756799a1dc.png)
![5](https://cloud.githubusercontent.com/assets/6071315/19723873/70733390-9b8e-11e6-8284-3864dc05e193.png)

**Comment by darekh93** [comment]
I have the same problem

**Comment by funkjedi** [comment]
Fixed in 1.7.14.

**Comment by Ma3oBblu** [comment]
thanks a lot!
