### ISSUE TITLE
Newest ACF (5.5.3) with newest addons causes fatal error.

### ISSUE THREAD

**Issue by riverofjanuary** [funkjedi/acf-qtranslate#84]
Hi,

I get this error with ACF PRO (full license) 5.3.10 and qtranslate-x 3.4.8 and acf-qtranslate 1.7.17

`Fatal error: Call to undefined method acf_qtranslate_acf_5_wysiwyg::add_filters() in /home/<MYDIRECTORYREMOVED>/wp-content/plugins/acf-qtranslate/src/acf_5/fields/wysiwyg.php on line 38`

If i downgrade ACF to 5.5.2 (but leave everything else at newest version), all works like a charm. Thoughts?

**Comment by funkjedi** [comment]
The `add_filters` function was added in ACF PRO 5.4.6 that's why you're getting the error when using ACF PRO 5.3.10. You should upgrade to the latest version of ACF PRO, 5.5.3 as of today.

**Comment by riverofjanuary** [comment]
You're right! This was a big oversight.
