### ISSUE TITLE
ACF Pro 5.5.4 - Error using ‘wp_prepare_attachment_for_js’ function

### ISSUE THREAD

**Issue by stilografico** [funkjedi/acf-qtranslate#87]
Hi,
since several time I use in my custom themes the function “wp_prepare_attachment_for_js” to print responsive images with values coming from wp native thumbnails and ACF images fields.
I just updated ACF to the newest release 5.5.4 and got this error.

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'acf_qtranslate_acf_5_file' does not have a method 'wp_prepare_attachment_for_js' in ../wp-includes/class-wp-hook.php on line 298

I just commented line 47 in this file acf-qtranslate/src/acf_5/fields/file.php
`add_filter('wp_prepare_attachment_for_js', array($this, 'wp_prepare_attachment_for_js'), 10, 3);`

The error disappears but I guess now ACF Q-translate does not extends images translations any more.

I'm mostly a frontend so not confident at all with PHP classes and objects.
Any help?

**Comment by funkjedi** [comment]
Just pushed out an updated version. The filter was removed from the File field in ACF 5.5.4 which was just released this morning.

**Comment by stilografico** [comment]
Thank you @funkjedi 
Since I'm on development stage on this particular project I decided to downgrade ACFpro and looking for next versions of your plugin.
Thanks for your prompt help

**Comment by ghost** [comment]
Hello,

Just to let you know that fresh ACF update (5.8.3) results in the same error. Disabling line 75 of /src/acf_5/fields/image.php resolves the issue for me (though I'm not pro enough to determine actual reason and the possible consequences of disabling).
