### ISSUE TITLE
acf()->fields->register_field_type error

### ISSUE THREAD

**Issue by jooj84** [funkjedi/acf-qtranslate#98]
Hi i have installated acf qtranslate on  a wb site with: acf pro 5.
Once the plugin is activated php die

Wp debug tel me this
Notice: Undefined property: acf::$fields in /****/wp-content/plugins/acf-qtranslate/src/acf_5/acf.php on line 36

Fatal error: Call to a member function register_field_type() on null in /***/wp-content/plugins/acf-qtranslate/src/acf_5/acf.php on line 36
hera are the lines that seems to make error
	acf()->fields->register_field_type(new acf_qtranslate_acf_5_text($this->plugin));
		acf()->fields->register_field_type(new acf_qtranslate_acf_5_textarea($this->plugin));
		acf()->fields->register_field_type(new acf_qtranslate_acf_5_wysiwyg($this->plugin));
		acf()->fields->register_field_type(new acf_qtranslate_acf_5_image($this->plugin));
		acf()->fields->register_field_type(new acf_qtranslate_acf_5_file($this->plugin));

How can i fix this?

**Comment by funkjedi** [comment]
You need to upgrade ACF to at least 5.4.0.
